repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.3.4
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
repos:
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.12.1
  hooks:
  - id: gersemi
    args: ["-i", "."]
repos:
-   repo: local
    hooks:
    -   id: wpiformat
        name: wpiformat
        entry: ./.github/workflows/run-wpiformat.py
        language: system
        pass_filenames: false
