name: Make conan packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix: 
        os: ["ubuntu-latest", "windows-latest"]


    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install freeglut3-dev -y
        fi
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run package script
      env:
        CONAN_PASS: ${{ secrets.CONAN_PASS }}
      run: |
        conan config install ./config/remotes.json
        python ./build_all_packages.py
        
