name: Package And Test Wpilib

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                config: [dbg_shared, dbg_static, rel_shared, rel_static]
        steps:
            - name: Checkout 
              uses: actions/checkout@v3

            - name: Get Conan
              uses: turtlebrowser/get-conan@v1.2

            - name: Create default profile
              run: conan profile detect

            - name: Make Wpicommon package
              working-directory: ./wpicommon
              run: |
                conan create . --pr ../.github/ci_conan_profiles/${{ matrix.config }}

            - name: Make Wpiutil package
              working-directory: ./wpiutil
              run: | 
                conan create . --pr ../.github/ci_conan_profiles/${{ matrix.config }}

