name: Package And Test Wpilib

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                config: [dbg_shared, dbg_static, rel_shared, rel_static]
                pi_target: [true, false]
                rio_target: [true, false]
                exclude:
                  - pi_target: true
                    rio_target: true
                  - os: macos-latest

        env:
          PROFILE_NAME: ${{ (matrix.rio_target == true && matrix.pi_target == false) && '--profile:host ../.github/ci_conan_profiles/rio_toolchain' || (matrix.rio_target == false && matrix.pi_target == true) && '--profile:host ../.github/ci_conan_profiles/pi_toolchain' || '' }}

        steps:
            - name: Checkout 
              uses: actions/checkout@v3

            - name: Get Conan
              uses: turtlebrowser/get-conan@v1.2

            - name: Create default profile
              run: conan profile detect

            - name: Make Wpicommon package
              working-directory: ./wpicommon
              run: |
                conan create .

            - name: Rio toolchain
              if: ${{ matrix.rio_target }}
              working-directory: ./riotoolchain
              run: |
                conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{ matrix.config }} --profile:host ../.github/ci_conan_profiles/rio_toolchain

            - name: Pi toolchain
              if: ${{ matrix.pi_target }}
              working-directory: ./pitoolchain
              run: |
                conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{ matrix.config }} --profile:host ../.github/ci_conan_profiles/pi_toolchain

            - name: Make Wpiutil package
              working-directory: ./wpiutil
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}
                               
            - name: List packages
              run: conan list wpiutil/2023.4.3:*

            - name: Make Wpinet package
              working-directory: ./wpinet
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}

            - name: Make Opencv package
              working-directory: ./opencv
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}            

            - name: Make Cscore package
              working-directory: ./cscore
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}

            - name: Make Ntcore package
              working-directory: ./ntcore
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}

            - name: Make CameraServer package
              working-directory: ./cameraserver
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}

            - name: Make Wpimath package
              working-directory: ./wpimath
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}

            - name: Make AprilTag package
              working-directory: ./apriltag
              run: conan create . --profile:build default --profile:build ../.github/ci_conan_profiles/${{matrix.config}} --profile:host default --profile:host ../.github/ci_conan_profiles/${{matrix.config}} ${{env.PROFILE_NAME}}